name: koncepto
description: A Bachelor Diploma project. 
             Connect the IOT device to network and manage it through koncepto.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies: 
  flutter:
    sdk: flutter
  get: ^4.6.5
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  data_table_2: ^2.3.5
  charts_flutter: ^0.12.0
  web_socket_channel: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.6
  get_storage: ^2.0.3
  intl: ^0.17.0
  http: ^0.13.5
  flutter_secure_storage: ^6.0.0
  flutter_libserialport: ^0.3.0
  ffi: ^2.0.1
  usb_device: ^0.0.7
  auto_route: ^5.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/